type Material = { filename: string; title: string; description: string; content: string };

const common = `# CrececonIA · Construye una página desde cero con inteligencia artificial\n\nDomingo 23 de agosto · Clase práctica en vivo\n\n`;

export const CLASS_MATERIALS: Record<string, Material> = {
  "checklist-preclase": { filename: "01-checklist-preclase.md", title: "Checklist preclase", description: "Todo lo que necesitas dejar listo antes de conectarte.", content: common + `## 30 minutos antes\n\n- [ ] Computador con cargador y conexión estable.\n- [ ] Una idea acotada: landing, servicio, portafolio o página de negocio.\n- [ ] Claude Code o Codex Desktop instalado e iniciado sesión.\n- [ ] Cuenta de GitHub verificada.\n- [ ] Cuenta de Vercel creada con GitHub.\n- [ ] Carpeta vacía creada para el proyecto.\n- [ ] Dos referencias (URL o screenshots) guardadas.\n- [ ] Texto mínimo: nombre, oferta, CTA y datos de contacto.\n\n## Durante la clase\n\n- [ ] Trabajar con audífonos y el chat visible.\n- [ ] Copiar prompts, pero reemplazar campos entre corchetes.\n- [ ] Guardar avances con commits pequeños.\n- [ ] Compartir bloqueos con captura + mensaje de error.\n` },
  brief: { filename: "02-plantilla-brief-web.md", title: "Plantilla de brief", description: "La especificación mínima antes de pedir código.", content: common + `# BRIEF · [Nombre del proyecto]\n\n## Resultado\n- **Qué debe lograr la página:**\n- **Acción principal (CTA):**\n- **Cómo sabremos que funciona:**\n\n## Audiencia\n- **Quién llega:**\n- **Problema o deseo principal:**\n- **Qué necesita entender rápido:**\n\n## Oferta y mensaje\n- **Oferta:**\n- **Diferenciador / prueba:**\n- **Tono de voz:**\n- **Palabras que sí / no usar:**\n\n## Contenido y secciones\n1. Hero: \n2. Problema / beneficio:\n3. Oferta / servicios:\n4. Prueba social / confianza:\n5. Preguntas frecuentes:\n6. CTA final:\n\n## Límites\n- No inventar testimonios, precios, logos ni datos.\n- [Agregar restricciones propias]\n` },
  mapa: { filename: "03-mapa-de-informacion.md", title: "Mapa de información", description: "Ordena páginas, secciones, mensajes y acciones.", content: common + `# Mapa de información · [Proyecto]\n\n## Página principal\n\n| Sección | Pregunta que responde | Contenido | Acción |\n| --- | --- | --- | --- |\n| Hero | ¿Qué es y para quién? | Titular + bajada + imagen | CTA principal |\n| Beneficios | ¿Por qué importa? | 3 beneficios | Ver oferta |\n| Oferta | ¿Qué recibo? | Servicio/producto | Contactar/comprar |\n| Confianza | ¿Por qué creer? | Casos, datos o proceso | Ver más |\n| FAQ | ¿Qué objeciones quedan? | 4-6 respuestas | CTA final |\n\n## Próximas páginas\n\n1. [Página] — necesidad que resuelve — prioridad [alta/media/baja].\n2. [Página] — necesidad que resuelve — prioridad [alta/media/baja].\n3. [Página] — necesidad que resuelve — prioridad [alta/media/baja].\n` },
  readme: { filename: "04-readme-contexto-para-agentes.md", title: "README y contexto", description: "Plantilla de memoria externa para que el agente trabaje con criterio.", content: common + `# README · [Proyecto]\n\n## Propósito\n[Qué construye esta web y cuál es su CTA.]\n\n## Comandos\n\`\`\`bash\nnpm install\nnpm run dev\nnpm run build\n\`\`\`\n\n## Reglas para el agente\n1. Lee BRIEF.md, DECISIONES.md y TAREAS.md antes de editar.\n2. Propón un plan para cambios que afecten más de una sección.\n3. No agregues dependencias, integraciones ni variables de entorno sin explicar por qué.\n4. Prioriza móvil, accesibilidad, textos reales y cambios pequeños.\n5. Ejecuta el build y reporta resultado antes de cerrar una tarea.\n\n# DECISIONES.md\n- [Fecha] Decisión — motivo — impacto.\n\n# TAREAS.md\n- [ ] Próxima tarea con resultado verificable.\n\n# REFERENCIAS.md\n- URL / screenshot — patrón útil — no copiar textos, marca ni assets.\n` },
  prompts: { filename: "05-prompts-construir-iterar-corregir.md", title: "Prompts de construcción", description: "Prompts listos para adaptar sin pedir cambios difusos.", content: common + `## 1. Construir\n\n\`\`\`text\nLee README.md, BRIEF.md, DECISIONES.md y REFERENCIAS.md.\nPropón un plan de archivos para una primera versión responsive.\nNo edites todavía: explica el orden, riesgos y qué información falta.\n\`\`\`\n\n## 2. Implementar\n\n\`\`\`text\nImplementa sólo la primera versión definida en el plan.\nPrioriza 390px, contenido real del brief y una CTA funcional.\nNo inventes testimonios, precios ni integraciones. Ejecuta el build al terminar y resume los archivos modificados.\n\`\`\`\n\n## 3. Iterar visualmente\n\n\`\`\`text\nEn el screenshot adjunto, el problema es [describir observable].\nAjusta sólo [sección] para lograr [resultado medible].\nMantén el resto de la página y revisa móvil + escritorio. Muéstrame el plan antes de editar.\n\`\`\`\n\n## 4. Corregir\n\n\`\`\`text\nEl build muestra este error: [pegar error completo].\nDiagnostica la causa raíz, propone la reparación mínima y espera mi aprobación antes de modificar dependencias o configuración.\n\`\`\`\n` },
  publicacion: { filename: "06-checklist-github-vercel.md", title: "Checklist GitHub y Vercel", description: "Respalda y publica sin subir información sensible.", content: common + `## GitHub\n- [ ] Repositorio correcto creado.\n- [ ] .gitignore incluye .env y archivos locales.\n- [ ] No hay claves, contraseñas o datos privados en archivos a subir.\n- [ ] Primer commit describe el cambio.\n- [ ] Push a GitHub confirmado.\n\n## Vercel\n- [ ] Cuenta conectada a GitHub.\n- [ ] Repositorio importado.\n- [ ] Framework y comando de build revisados.\n- [ ] Variables de entorno configuradas sólo en Vercel si aplica.\n- [ ] Deploy exitoso y URL abierta.\n- [ ] Nuevo push genera un nuevo deploy.\n` },
  qa: { filename: "07-checklist-qa.md", title: "Checklist QA", description: "La revisión rápida antes de compartir una URL.", content: common + `- [ ] La propuesta se entiende en 5 segundos.\n- [ ] CTA visible y funcional en móvil y escritorio.\n- [ ] Enlaces internos, WhatsApp, mail y formularios probados.\n- [ ] No quedan textos Lorem ipsum, datos inventados ni marcadores ocultos.\n- [ ] Ortografía, tildes, precios y teléfonos revisados.\n- [ ] Texto legible, contraste suficiente y botones de al menos 44px.\n- [ ] No hay desborde horizontal en 390px.\n- [ ] Imágenes tienen texto alternativo cuando aportan contenido.\n- [ ] Build sin errores y consola sin errores relevantes.\n- [ ] Commit y deployment final identificables.\n` },
  "reto-7-dias": { filename: "08-reto-7-dias.md", title: "Reto de 7 días", description: "Convierte la primera URL en una presencia web sólida.", content: common + `# Día 1 · Publica V1\nCompleta la QA y comparte tu URL con tres personas.\n\n# Día 2 · Mensaje\nAnota qué no entendieron. Mejora titular, bajada y CTA.\n\n# Día 3 · Prueba\nAgrega proceso, caso real o evidencia verificable.\n\n# Día 4 · Móvil\nRevisa el recorrido completo en 390px y corrige fricción.\n\n# Día 5 · Contenido\nEscribe una FAQ y una página secundaria prioritaria.\n\n# Día 6 · Conversión\nRevisa enlaces y mide una acción simple: clic, mensaje o formulario.\n\n# Día 7 · Decisión\nDefine el próximo bloque: SEO, portafolio, catálogo, agenda o implementación.\n` },
  recursos: { filename: "09-recursos-recomendados.md", title: "Recursos y herramientas", description: "Qué usar, para qué y qué revisar antes de conectar.", content: common + `| Recurso | Para qué sirve | Revisión antes de usar |\n| --- | --- | --- |\n| Claude Code / Codex | Construir y editar código | Carpeta abierta y permisos de comandos |\n| GitHub | Historial y respaldo | Repositorio, .gitignore y visibilidad |\n| Vercel | Deploy y URL pública | Proyecto, logs, variables de entorno |\n| Navegador / screenshots | Referencias y QA | Derechos de uso y contenido propio |\n| WhatsApp / formulario | CTA de contacto | Número, mensaje prellenado, privacidad |\n\n## Conecta con cuidado\n\n- Correo, Drive completo, facturación, bases de datos de clientes y redes sociales con permisos de publicación.\n- Cualquier skill o conector que pida acceso a secretos o permita ejecutar cambios en producción.\n- Dependencias cuyo origen, costo o mantenimiento no puedes explicar.\n` },
};

export function getClassMaterial(id: string | null) {
  return id ? CLASS_MATERIALS[id] ?? null : null;
}
