"use client";
import { useCallback, useEffect, useState } from "react";

type Dashboard = {
  generatedAt: string;
  metrics: { paid: number; revenue: number; salesToday: number; revenueToday: number; averageTicket: number; paymentConversion: number; landingViews: number; checkoutStarts: number; checkoutRate: number; visitorConversion: number; salesLastHour: number; activeReservations: number; deliveryRate: number; bounceRate: number; deliveryFailures: number };
  orders: Array<{ commerce_order: string; email: string; amount_minor: number; status: string; paid_at: string | null; created_at: string }>;
  deliveries: Array<{ email: string; delivery_kind: string; status: string; provider_status: string | null; sent_at: string | null; delivered_at: string | null; last_error: string | null }>;
  channels: Array<{ source: string; sales: number; revenue: number }>;
};
const clp = (value: number) => `$${value.toLocaleString("es-CL")}`;

export default function WorkshopDashboardLive({ adminKey, initial }: { adminKey: string; initial: Dashboard }) {
  const [data,setData] = useState(initial), [error,setError] = useState("");
  const refresh = useCallback(async () => { const response = await fetch("/api/admin/workshop-dashboard",{headers:{"x-admin-key":adminKey},cache:"no-store"}); const next=await response.json(); if(!response.ok) throw new Error(next.error); setData(next); setError(""); },[adminKey]);
  useEffect(()=>{const id=window.setInterval(()=>refresh().catch((reason)=>setError(reason.message)),15000);return()=>window.clearInterval(id)},[refresh]);
  const cards = [["Visitas",data.metrics.landingViews],["Inicio checkout",data.metrics.checkoutStarts],["Visita → checkout",`${data.metrics.checkoutRate}%`],["Visita → venta",`${data.metrics.visitorConversion}%`],["Entradas pagadas",data.metrics.paid],["Recaudación",clp(data.metrics.revenue)],["Ventas hoy",data.metrics.salesToday],["Monto hoy",clp(data.metrics.revenueToday)],["Finalización de pago",`${data.metrics.paymentConversion}%`],["Última hora",data.metrics.salesLastHour],["Entrega de email",`${data.metrics.deliveryRate}%`],["Rebotes",`${data.metrics.bounceRate}%`]];
  return <div className="workshop-admin-live"><div className="workshop-admin-livebar"><span><i/> Actualización cada 15 s</span><small>{new Date(data.generatedAt).toLocaleTimeString("es-CL")}</small><button onClick={()=>refresh().catch((reason)=>setError(reason.message))}>Actualizar</button></div>{error&&<p className="workshop-admin-error">{error}</p>}<section className="workshop-admin-kpis">{cards.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="workshop-admin-intelligence"><article><span>Lectura rápida</span><p>{data.metrics.paymentConversion>=70?"El checkout está cerrando bien.":"Hay fricción entre la reserva y el pago; revisa abandonos y errores de Flow."}</p></article><article><span>Operación</span><p>{data.metrics.deliveryFailures===0?"No hay entregas fallidas registradas.":`${data.metrics.deliveryFailures} correos requieren revisión o reintento.`}</p></article><article><span>Demanda</span><p>{data.metrics.salesLastHour>0?`${data.metrics.salesLastHour} ventas en la última hora: mantén visible la prueba social de ventas del día.`:"Sin ventas en la última hora. Prioriza tráfico cualificado antes de cambiar el precio."}</p></article></section><section className="workshop-admin-table"><h2>Ventas por canal</h2><div><table><thead><tr><th>Fuente</th><th>Ventas</th><th>Recaudación</th></tr></thead><tbody>{data.channels.map((channel)=><tr key={channel.source}><td>{channel.source}</td><td>{channel.sales}</td><td>{clp(channel.revenue)}</td></tr>)}</tbody></table></div></section><section className="workshop-admin-table"><h2>Compras recientes</h2><div><table><thead><tr><th>Correo</th><th>Estado</th><th>Monto</th><th>Fecha</th></tr></thead><tbody>{data.orders.slice(0,50).map((order)=><tr key={order.commerce_order}><td>{order.email}</td><td>{order.status}</td><td>{clp(order.amount_minor)}</td><td>{new Date(order.paid_at??order.created_at).toLocaleString("es-CL")}</td></tr>)}</tbody></table></div></section><section className="workshop-admin-table"><h2>Salud de correos</h2><div><table><thead><tr><th>Correo</th><th>Mensaje</th><th>Estado proveedor</th><th>Error</th></tr></thead><tbody>{data.deliveries.slice(0,80).map((item,index)=><tr key={`${item.email}-${item.delivery_kind}-${index}`}><td>{item.email}</td><td>{item.delivery_kind}</td><td>{item.provider_status??item.status}</td><td>{item.last_error??"—"}</td></tr>)}</tbody></table></div></section></div>;
}
