import { NextResponse } from "next/server";
import { getSupabaseAdmin } from "@/lib/supabase";
import { WORKSHOP_PRODUCT_KEY } from "@/lib/workshop-product";
import { getWorkshopSettings } from "@/lib/workshop-settings";
export const dynamic="force-dynamic";
const authorized=(request:Request)=>Boolean(process.env.ADMIN_SECRET)&&(request.headers.get("x-admin-key")??new URL(request.url).searchParams.get("key"))===process.env.ADMIN_SECRET;
function optionalUrl(value:unknown,label:string){const text=typeof value==="string"?value.trim():"";if(!text)return null;const url=new URL(text);if(url.protocol!=="https:")throw new Error(`${label} debe ser una URL https.`);return url.toString()}
export async function GET(request:Request){if(!authorized(request))return NextResponse.json({error:"No autorizado."},{status:401});return NextResponse.json({settings:await getWorkshopSettings()})}
export async function PUT(request:Request){if(!authorized(request))return NextResponse.json({error:"No autorizado."},{status:401});const body=await request.json().catch(()=>null);try{const supportEmail=typeof body?.supportEmail==="string"?body.supportEmail.trim().toLowerCase():"";if(!/^\S+@\S+\.\S+$/.test(supportEmail)||typeof body?.roomEnabled!=="boolean")throw new Error("Configuración inválida.");const skillsPath=typeof body?.skillsStoragePath==="string"?body.skillsStoragePath.trim():"";if(skillsPath&&(skillsPath.includes("..")||skillsPath.startsWith("/")))throw new Error("La ruta del ZIP no es válida.");const{data,error}=await getSupabaseAdmin().rpc("upsert_workshop_settings",{p_product_key:WORKSHOP_PRODUCT_KEY,p_session_url:optionalUrl(body.sessionUrl,"Meet"),p_recording_url:optionalUrl(body.recordingUrl,"Grabación"),p_skool_url:optionalUrl(body.skoolUrl,"SKOOL"),p_skills_storage_path:skillsPath||null,p_support_email:supportEmail,p_room_enabled:body.roomEnabled});if(error)throw new Error(error.message);return NextResponse.json({settings:data?.[0]??null})}catch(reason){return NextResponse.json({error:reason instanceof Error?reason.message:"No se pudo guardar."},{status:400})}}
